strictness: medium
doc-warnings: false
test-warnings: false
autodetect: true
member-warnings: false

pep257:
  disable:
    - D202
    - D203
    - D205
    - D212
    - D213
    - D214
    - D215
    - D404
    - D405
    - D406
    - D407
    - D408
    - D409
    - D410
    - D411
    - D413
    - D415
    - D416
    - D417

pylint:
  disable:
    - too-many-arguments
