steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    pip install -U --no-deps https://github.com/mne-tools/mne-python/archive/main.zip
    pip install -r requirements_testing.txt

  displayName: 'Install dependencies'

- script: |
    pip install pytest-azurepipelines
    pytest pycrostates --junitxml=junit/test-results.xml --cov=pycrostates --cov-report=xml
  displayName: 'pytest'
