steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --progress-bar off --upgrade pip setuptools wheel
    python -m pip install --progress-bar off .[test]
    python -m pip uninstall -y mne
    python -m pip install --progress-bar off --no-deps https://github.com/mne-tools/mne-python/archive/main.zip
  displayName: 'Install dependencies'

- script: |
    mne sys_info -pd
  displayName: 'Display MNE config'

- script: |
    pytest pycrostates --junitxml=junit/test-results.xml --cov=pycrostates --cov-report=xml
  displayName: 'Run tests'
