name: "Get MNE testing dataset"
description: "A composite action to get MNE testing dataset from cache or remote."

runs:
  using: "composite"
  steps:
    - name: Get testing dataset version
      shell: bash
      run: curl https://raw.githubusercontent.com/mne-tools/mne-testing-data/master/version.txt -o mne_testing_data_version.txt
    - name: Cache testing dataset
      id: cache
      uses: actions/cache@v4
      with:
        key: mne-testing-${{ runner.os }}-${{ hashFiles('mne_testing_data_version.txt') }}
        path: ~/mne_data
    - name: Download testing dataset
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: python -c "import mne; mne.datasets.testing.data_path(verbose=True)"
    - name: Remove dataset version file
      shell: bash
      run: rm mne_testing_data_version.txt
