.. This (-*- rst -*-) format file contains commonly used link targets
   and name substitutions.  It may be included in many files,
   therefore it should only contain link targets and name
   substitutions.  Try grepping for "^\.\. _" to find plausible
   candidates for this list.

.. NOTE: reST targets are
   __not_case_sensitive__, so only one target definition is needed for
   nipy, NIPY, Nipy, etc...


.. python

.. _`mne-python`: http://mne.tools/mne-python-intro


.. citations

.. _`michel 2018`: https://doi.org/10.1016/j.neuroimage.2017.11.062

