.. This (-*- rst -*-) format file contains commonly used link targets
   and name substitutions.  It may be included in many files,
   therefore it should only contain link targets and name
   substitutions.  Try grepping for "^\.\. _" to find plausible
   candidates for this list.

.. NOTE: reST targets are
   __not_case_sensitive__, so only one target definition is needed for
   nipy, NIPY, Nipy, etc...


.. project

.. _project pypi: https://pypi.org/project/pycrostates/
.. _project conda: https://anaconda.org/conda-forge/pycrostates
.. _project github: https://github.com/vferat/pycrostates


.. mne

.. _mne stable: https://mne.tools/stable/index.html
.. _mne install: https://mne.tools/stable/install/index.html
.. _mne installers: https://mne.tools/stable/install/installers.html
